### ISSUE TITLE
Algebraic Questions

### ISSUE THREAD

**Issue by Wang-bit385** [theysy/Numerical_differentiation#1]
Hello respected teacher, I am a graduate student from Yanshan University in China. You can call me Xiao Wang. I am very grateful that you have been answering my questions. I wonder if you still remember. I am very interested in your constitutive model for anisotropic hardening and have been studying it. I am confused about the derivative of the yield function that I sent to you in the attachment. I have a basic understanding of tensors, but I don't understand the tensor operations here. Please help me with this. I also emailed the author of this article, but have not heard back. Please help me, I really need your help. Thank you.
<img width="356" alt="1" src="https://github.com/user-attachments/assets/3fcae8e7-cd7f-453e-a58c-9ee4e162b6fb">

**Comment by theysy** [comment]
The effective stress of HAH consists of (1) Fluctuating component and (2) Stable component.
The fluctuating component is to distort the yield surface based on the strain-path change indicator (cos X).
The stable component corresponds to the effective stress of a yield function.

To get the derivative of HAH model, you would better to take this as a composite function: G(f(x))
So, the basic algebra will be dG/dx = (dG/df)*(df/dx)
If f(x) is an yield function, then df/dx would be the derivative of yield function.

This derivation is not as complicated as you think.

Good luck!

**Comment by Wang-bit385** [comment]
I understand, thank you for your guidance. The study of constitutive models is like a roller coaster ride, where we often feel like we're going downhill and getting stuck in a rut. But sometimes, all we need is a turn in the right direction to make progress. Thank you again for your guidance.I have been trying to cut into the QPE model based on the "MML_U2.for" file you shared, and I have written code, but I keep getting the error "#ERROR: SIG_BAR_K=NaN INITIAL RESIDUAL 4.87782855354573". The model is not the problem, I have sent you the code and model to the  e-mail：theysy@postech.ac.kr。please review and correct me.

**Comment by theysy** [comment]
I think you misunderstand my volunteering.
You would better to solve your problem by doing "re-search" as every scientist does.
How to solve issues is quite simple: Read the code and find out the reason by YOURSELF.
If I keep helping you, you would rely on me, which is not good for your skill development.
